/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs311x_nguyenhongphap_quanlyvemaybay;

import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHAP
 */
public class FormVeMayBay extends javax.swing.JFrame {
    DefaultTableModel dtm;
    DSVMB a= new DSVMB();
    

    /**
     * Creates new form FormVeMayBay
     */
    public FormVeMayBay() {
        initComponents();
        dtm=new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"Ma san bay","Ngay bay","Don gia","So luong","Diem den","Thanh tien"});
        tblHienThi.setModel(dtm);
        btnLuuFile.setEnabled(false);
        btnThem.setEnabled(false);
        btnXoa.setEnabled(false);
        btnThem.setEnabled(false);
        btnNoiDia.setEnabled(false);
        btnXN.setEnabled(false);
        btnTim.setEnabled(false);
    }
    void xoaTable(){
        while (dtm.getRowCount()>0)
            dtm.removeRow(0);
    }
    void hienThiThongTinTable(ArrayList<VeMayBay>a){
        xoaTable();
        for (VeMayBay x : a)
            if (x instanceof NoiDia)
                dtm.addRow(new Object[]{x.getMaSanBay(),x.getNgayBay(),x.getDonGia(),x.getSoLuong(),((NoiDia) x).getTinh(),((NoiDia) x).tinhThanhTien()});
            else dtm.addRow(new Object[]{x.getMaSanBay(),x.getNgayBay(),x.getDonGia(),x.getSoLuong(),((XuatNgoai) x).getChauLuc(),((XuatNgoai) x).tinhThanhTien()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMaSanBay = new javax.swing.JLabel();
        lblNgayBay = new javax.swing.JLabel();
        lblDonGia = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblDiemDen = new javax.swing.JLabel();
        txtMaSanBay = new javax.swing.JTextField();
        txtNgayBay = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtDiemDen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHienThi = new javax.swing.JTable();
        btnDocFile = new javax.swing.JButton();
        btnLuuFile = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnNoiDia = new javax.swing.JButton();
        btnXN = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUAN LY VE MAY BAY");
        setResizable(false);

        lblMaSanBay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaSanBay.setText("Ma San Bay");

        lblNgayBay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgayBay.setText("Ngay Bay");

        lblDonGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDonGia.setText("Don Gia");

        lblSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSoLuong.setText("So Luong");

        lblDiemDen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiemDen.setText("Diem Den");

        txtMaSanBay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtNgayBay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtDonGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtDiemDen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblHienThi);

        btnDocFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDocFile.setText("Doc File");
        btnDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileActionPerformed(evt);
            }
        });

        btnLuuFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLuuFile.setText("Luu File");
        btnLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFileActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTim.setText("Tim");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnNoiDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNoiDia.setText("Tong Tien Ve ND");
        btnNoiDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoiDiaActionPerformed(evt);
            }
        });

        btnXN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXN.setText("Tong Tien Ve XN");
        btnXN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXNActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setText("Thoat");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSanBay)
                            .addComponent(lblNgayBay)
                            .addComponent(lblDonGia)
                            .addComponent(lblSoLuong)
                            .addComponent(lblDiemDen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiemDen, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSanBay, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDocFile)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuuFile)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnTim)
                        .addGap(18, 18, 18)
                        .addComponent(btnNoiDia)
                        .addGap(18, 18, 18)
                        .addComponent(btnXN)
                        .addGap(18, 18, 18)
                        .addComponent(btnThoat)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaSanBay)
                            .addComponent(txtMaSanBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNgayBay)
                            .addComponent(txtNgayBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDonGia)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSoLuong)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiemDen)
                            .addComponent(txtDiemDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocFile)
                    .addComponent(btnLuuFile)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnTim)
                    .addComponent(btnNoiDia)
                    .addComponent(btnXN)
                    .addComponent(btnThoat))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc= new JFileChooser();
        fc.showOpenDialog(null);
        String tenFile = fc.getSelectedFile().getPath();
        //JOptionPane.showMessageDialog(null, tenFile);
        a.docFile(tenFile);
        hienThiThongTinTable(a.getA());
        btnLuuFile.setEnabled(true);
        btnThem.setEnabled(true);
        btnXoa.setEnabled(true);
        btnThem.setEnabled(true);
        btnNoiDia.setEnabled(true);
        btnXN.setEnabled(true);
        btnTim.setEnabled(true);
        
    }//GEN-LAST:event_btnDocFileActionPerformed

    private void btnLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc= new JFileChooser();
        fc.showSaveDialog(null);
        String tenFile = fc.getSelectedFile().getPath();
        a.ghiFile(tenFile);
    }//GEN-LAST:event_btnLuuFileActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String ma, ngay, dd;
        double sl, dg;
        ma=txtMaSanBay.getText();
        ngay=txtNgayBay.getText();
        sl=Double.parseDouble(txtDonGia.getText());
        dg=Double.parseDouble(txtSoLuong.getText());
        dd=txtDiemDen.getText().trim();
        VeMayBay x;
        if (dd.equalsIgnoreCase("A")||dd.equalsIgnoreCase("My"))
            x=new XuatNgoai(dd, ma, ngay, dg, sl);
            else x=new NoiDia(dd, ma, ngay, dg, sl);
        if(a.themMoi(x)==true)
            hienThiThongTinTable(a.getA());
        else JOptionPane.showMessageDialog(null, "Khong them vi da co ma "+ma+" nay trong DS");
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String ma = JOptionPane.showInputDialog("Nhap ma can xoa");
        if(a.xoaTheoMa(ma)==true)
            hienThiThongTinTable(a.getA());
        else JOptionPane.showMessageDialog(null, "Khong co ma "+ma+" nay trong DS");
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
         String ma = JOptionPane.showInputDialog("Nhap ma can tim");
        VeMayBay x=a.timTheoMa(ma);
        if(x==null)JOptionPane.showMessageDialog(null, "Khong co ma "+ma+" nay trong DS");
        else JOptionPane.showMessageDialog(rootPane, x);
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnNoiDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoiDiaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Tong tien ve noi dia"+a.TongTienVeNoiDia());
    }//GEN-LAST:event_btnNoiDiaActionPerformed

    private void btnXNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXNActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Tong tien ve xuat ngoai"+a.TongTienVeXuatNgoai());
    }//GEN-LAST:event_btnXNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVeMayBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVeMayBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVeMayBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVeMayBay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVeMayBay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnLuuFile;
    private javax.swing.JButton btnNoiDia;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXN;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiemDen;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblMaSanBay;
    private javax.swing.JLabel lblNgayBay;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JTable tblHienThi;
    private javax.swing.JTextField txtDiemDen;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSanBay;
    private javax.swing.JTextField txtNgayBay;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
