/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cs311x_hanghoa_nguyenhongphap;

import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHAP
 */
public class QUANLYHANGHOA extends javax.swing.JFrame {
    DefaultTableModel dtm;
    DSHH a= new DSHH();
    /**
     * Creates new form QUANLYHANGHOA
     */
    public QUANLYHANGHOA() {
        initComponents();
        dtm=new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"Ma hang", "Ngay nhap","Don gia","So luong","Nguon","Thanh tien"});
        btlHienThi.setModel(dtm);
        btnLuuFile.setEnabled(false);
        btnThem.setEnabled(false);
        btnXoa.setEnabled(false);
        btnTim.setEnabled(false);
        btnTongTienDM.setEnabled(false);
        btnTongTienTC.setEnabled(false);
    }
    void xoaTable(){
        while(dtm.getRowCount()>0)
            dtm.removeRow(0);
    }
    void hienThiThongTinTable(ArrayList<HangHoa>a){
        xoaTable();
        for (HangHoa x : a) {
            if(x instanceof HangDienMay)
                dtm.addRow(new Object[]{x.getMaHang(),x.getNgayNhap(),x.getSoLuong(),x.getDonGia(),((HangDienMay) x).getNoiSanXuat(),((HangDienMay) x).tinhThanhTien()});
            else dtm.addRow(new Object[]{x.getMaHang(),x.getNgayNhap(),x.getSoLuong(),x.getDonGia(),((HangThuCong) x).getNhaSanXuat(),((HangThuCong) x).tinhThanhTien()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        lblMaHang = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLuuFile = new javax.swing.JButton();
        btnDocFile = new javax.swing.JButton();
        btnTongTienTC = new javax.swing.JButton();
        btnTongTienDM = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        txtSanXuat = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtMaHang = new javax.swing.JTextField();
        txtNgayNhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        btlHienThi = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUAN LY HANG HOA");
        setResizable(false);

        lblMaHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaHang.setText("Ma Hang");
        lblMaHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Ngay Nhap");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Don Gia");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("So Luong");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("San Xuat");

        btnLuuFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLuuFile.setText("Luu File");
        btnLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFileActionPerformed(evt);
            }
        });

        btnDocFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDocFile.setText("Doc File");
        btnDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileActionPerformed(evt);
            }
        });

        btnTongTienTC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTongTienTC.setText("Tong Tien TC");
        btnTongTienTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongTienTCActionPerformed(evt);
            }
        });

        btnTongTienDM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTongTienDM.setText("Tong Tien DM");
        btnTongTienDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongTienDMActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTim.setText("Tim");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtSanXuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtDonGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtMaHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaHangActionPerformed(evt);
            }
        });

        txtNgayNhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btlHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(btlHienThi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addComponent(txtNgayNhap))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDocFile, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaHang)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(txtSoLuong)
                                .addComponent(txtDonGia)
                                .addComponent(txtMaHang, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnLuuFile)
                                .addGap(18, 18, 18)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTongTienDM)
                        .addGap(18, 18, 18)
                        .addComponent(btnTongTienTC)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaHang)
                            .addComponent(txtMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSanXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuuFile)
                    .addComponent(btnTongTienDM)
                    .addComponent(btnTim)
                    .addComponent(btnXoa)
                    .addComponent(btnThem)
                    .addComponent(btnDocFile)
                    .addComponent(btnTongTienTC))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc= new JFileChooser();
        fc.showSaveDialog(null);
        String tenFile=fc.getSelectedFile().getPath();
        a.ghiFile(tenFile);
    }//GEN-LAST:event_btnLuuFileActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        
        String ma= JOptionPane.showInputDialog("Nhap ma can tim");
        
        HangHoa x=a.timTheoMa(ma);
        if(x==null)JOptionPane.showMessageDialog(null, "Khong co ma "+ma+" trong danh sach");
        else JOptionPane.showMessageDialog(rootPane, x);
        
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc= new JFileChooser();
        fc.showOpenDialog(null);
        String tenFile=fc.getSelectedFile().getPath();
        //JOptionPane.showConfirmDialog(null, tenFile);
        a.docFile(tenFile);
        hienThiThongTinTable(a.getA());
        btnLuuFile.setEnabled(true);
        btnThem.setEnabled(true);
        btnXoa.setEnabled(true);
        btnTim.setEnabled(true);
        btnTongTienDM.setEnabled(true);
        btnTongTienTC.setEnabled(true);
    }//GEN-LAST:event_btnDocFileActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        
        String ma, ngay, nsx;
        double sl,dg;
        ma=txtMaHang.getText();
        ngay=txtNgayNhap.getText();
        sl=Double.parseDouble(txtSoLuong.getText());
        dg=Double.parseDouble(txtDonGia.getText());
        nsx=txtSanXuat.getText().trim();
        HangHoa x;
        if(nsx.equalsIgnoreCase("TN")||nsx.equalsIgnoreCase("NK"))
            x= new HangDienMay(nsx, ma, ngay, sl, dg);
        else x= new HangThuCong(nsx, ma, ngay, sl, dg);
        if(a.themMoi(x)==true)
            hienThiThongTinTable(a.getA());
        else JOptionPane.showMessageDialog(null, "Khong them vi da co ma "+ma+" trong danh sach");
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String ma= JOptionPane.showInputDialog("Nhap ma can xoa");
        if(a.xoaTheoMa(ma)==true)
            hienThiThongTinTable(a.getA());
        else JOptionPane.showMessageDialog(null, "Khong co ma "+ma+" nay trong danh sach");
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTongTienDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongTienDMActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Tong tien hang dien may ="+a.tongTienHangDienMay());
        
    }//GEN-LAST:event_btnTongTienDMActionPerformed

    private void btnTongTienTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongTienTCActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Tong tien hang thu cong ="+a.tongTienHangThuCong());
        
    }//GEN-LAST:event_btnTongTienTCActionPerformed

    private void txtMaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaHangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtMaHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QUANLYHANGHOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QUANLYHANGHOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QUANLYHANGHOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QUANLYHANGHOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QUANLYHANGHOA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable btlHienThi;
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnLuuFile;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTongTienDM;
    private javax.swing.JButton btnTongTienTC;
    private javax.swing.JButton btnXoa;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaHang;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaHang;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtSanXuat;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
